/**
 * 
 */
package com.HS.enums;

/**
 * @author hemasundar
 *
 */
public enum StepActions {
    OPENBROWSER, GOBACK, GOFORWARD, NAVIGATEURL, REFRESH, CHECK, UNCHECK, CLOSEBROWSER, CLOSEALLBROWSERS, CLICKOBJECT, MOUSEOVER, DOUBLECLICK, ENTERDATA, FIREEVENT, ENTERUNIQUEDATA, KEYPRESS, WAIT, SELECTITEM, SELECTITEMBYINDEX, GETOBJECTPROPERTY, SETVARIABLE, GETPAGEPROPERTY, VERIFYTEXTPRESENT, COMPAREDBRESULTS, INPUTFILENAME, RANDOMNAMEGENERATOR, VERIFYOBJECTPROPERTY, VERIFYPAGEPROPERTY, VERIFYOBJECTPRESENT, VERIFYOBJECTNOTPRESENT, WAITFORELEMENT, GETRESULTFROMDB, UPDATEDB, CUTREQUIREDIMAGE, COMPAREIMAGES, VERIFYOBJECTSIZE, VERIFYFONTNAME, VERIFYFONTSIZE, VERIFYFONTWEIGHT, VERIFYCOLOR, PRESENTEDBYURLINSPECT, VERIFYSIZE, SWITCHTOIFRAME, VERIFYSERVERCALL, VERIFYCOLORCHANGE, WINDOWRESIZE, VERIFYTITLE, VERIFYIMAGEPIXEL, VERIFYURL, VERIFYTEXTPRESENCEINREDIRECTEDURL, EXPLICITWAIT, GETIMAGENUMBERINGALLERY, CLICKTILLLASTIMAGE, VERIFYTEXT, SENDKEYS;
}
